#!/bin/sh

# update sudo permissions, now that we added a sudoers.d file
sudo service sudo restart

# install nvm to ensure correct node version can be used
echo "Installing NVM and node v 6.11.1 under user openhim_cert_updater..."; ## NOTE: packages build-essential libssl-dev are required for NVM
sudo su openhim_cert_updater bash -c 'curl https://raw.githubusercontent.com/creationix/nvm/v0.11.1/install.sh | bash'
sudo su openhim_cert_updater bash -c 'source $HOME/.nvm/nvm.sh && nvm install 6.11.1'

echo "(!) Your installation is not yet complete! You must create the openhim-cert-updater configuration file. Information on how to do this can be found by running 'sudo openhim-cert-updater -c'."

exit 0;
